name = "FasciolaDistribution"
uuid = "36235078-cee6-484f-9e3b-adc365a31144"
authors = ["tiemvanderdeure <tiemvanderdeure@gmail.com>"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
BibParser = "13533e5b-e1c2-4e57-8cef-cac5e52f6474"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
GBIF2 = "dedd4f52-e074-43bf-924d-d6bce14ad628"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Maxnet = "81f79f80-22f2-4e41-ab86-00c11cf0f26f"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RasterDataSources = "3cb90ccd-e1b6-4867-9617-4276c8b2ca36"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SummaryTables = "6ce4ecf0-73a7-4ce3-9fb4-80ebfe887b60"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UnicodeFun = "1cfade01-22cf-5700-b092-accc4b62d6e1"
WriteDocx = "d049ceea-54ee-41d7-a26f-ba29db3b6599"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
DiskArrays = "0.4.9"
HDF5_jll = "=1.14.3"
NearestNeighbors = "0.4.21"
StaticArrays = "1.9.12"
Statistics = "1.11.1"
